### ISSUE TITLE
combing two graphs?

### ISSUE THREAD

**Issue by kittyzxu** [Statistical-Connectomics-Sp15/intro#10]
Have people done the type of work where they 
1) create one graph that connects different parts of the human brain based on its anatomical and structural features and connections;
2) create a second graph that's based on the functional connectives among the regions of the brain;
3) sum the two graphs together;
4) What would they get as a result and how would the combined two graphs inform about our brain?

**Comment by jovo** [comment]
yup. @gkiar - can you put a couple papers in the google drive that compare
functional and structural connectomes? lemme know if you don't find any.

@kittzxu - they don't tend to add them, rather, compare them. for now. we
have a draft paper on this, that i hope will go on the arxiv soon, when it
does, i'll share...

**Comment by kittyzxu** [comment]
Thank you for the answer!

**Comment by gkiar** [comment]
Getting access to the google drive, but try this article:
http://www.nature.com/nrn/journal/v10/n3/pdf/nrn2575.pdf
