### ISSUE TITLE
What "Connectomics" refers to

### ISSUE THREAD

**Issue by SandyaS72** [Statistical-Connectomics-Sp15/intro#14]
At first glance, "connectomics" seems like a very general term, but most of the literature around it specifically refers to structural connectomes as opposed to functional. Is this a distinction that was made deliberately, if so why and who decided it, or is it something that's just kind of come to be accepted as an unstated convention?

**Comment by willgray** [comment]
In general, people use and abuse connectome to mean lots of different things.  In particular, people do talk about functional (often fMRI) connectomes.  But agree the history seems centered on structure, which allows us to make a map before we figure out how much the pathways are used:

Olaf Sporns' definition from a paper in 2005 is the standard, and has therefore been cited almost 1000 times:  http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0010042

...The purpose of this article is to discuss research strategies aimed at a comprehensive structural description of the network of elements and connections forming the human brain. We propose to call this dataset the human “connectome,” and we argue that it is fundamentally important in cognitive neuroscience and neuropsychology...
