### ISSUE TITLE
Articles

### ISSUE THREAD

**Issue by aceeccc** [Statistical-Connectomics-Sp15/intro#24]
When should we start looking through the articles and seeing which we would prefer to present?

**Comment by jovo** [comment]
after this week.

On Mon, Feb 2, 2015 at 11:02 AM, Michelle Chyn <notifications@github.com>
wrote:

>  When should we start looking through the articles and seeing which we
> would prefer to present?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/24>.
>



-- 
it's our dream
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
