### ISSUE TITLE
Important Edges

### ISSUE THREAD

**Issue by akim1** [Statistical-Connectomics-Sp15/intro#26]
Along the lines of kristinmg's question, not all edges/nodes are equally important, and for instance, a node with many edges may be biologically more important than a node with one or two edges (or vice versa). In these instances, reducing the information of the graph to one or two dimensions seems more appropriate than trying to process the complete graph. What are some information that can be gleaned from using a whole graph that would otherwise would not be obtainable from using simple features?

**Comment by jovo** [comment]
take any 2 features.
what does 1 feature tell you about the graph.
what does the other.
this tells you what 1 feature is missing from just one other feature.
now extrapolate that to 2^n^2 features...

On Mon, Feb 2, 2015 at 3:18 PM, akim1 <notifications@github.com> wrote:

>  Along the lines of kristinmg's question, not all edges are not equally
> important, and for instance, a node with many edges may be biologically
> more important than a node with one or two edges (or vice versa). In these
> instances, reducing the information of the graph to one or two dimensions
> seems more appropriate than trying to process the complete graph. What are
> some information that can be gleaned from using a whole graph that using
> simple features wouldn't provide?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/26>.
>



-- 
it's our dream
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
