### ISSUE TITLE
Other cells in the brain

### ISSUE THREAD

**Issue by allym** [Statistical-Connectomics-Sp15/intro#29]
On the first day we briefly mentioned the presence of non-neuronal cells in the brain. While these cells (astrocytes, glial cells, etc) aren't directly involved in the physical connections and information transfer like neurons are, are there ways we include their supportive effects in our graphs (possibly through changing the weights, e.g.)?

**Comment by mrjiaruiwang** [comment]
I feel that since there are many functions for non-neuronal cells in the brain, it would depend on their function. From the way we have been setting up these graphs in class though, it seems like we tend to just ignore these effects.

**Comment by SandyaS72** [comment]
I don't know about when you look at it from a neuron by neuron perspective, but in lots of cases, you look at connectivity on a larger more region by region basis, where nodes are regions. And in cases where you're measuring functional connectivity, which is based on activity, if the other cells affected activity in some way, I'm guessing that would get accounted for.

**Comment by allym** [comment]
Thanks you guys!

**Comment by sgomezr** [comment]
As @SandyaS72 's hinted, some  of the other cells present in the brain affect activity, in the wya that they control blood flow, manage neuron's energy supply, the flow of the CSF and ISF, and are in charge of the uptake of neurontransmitters after neural activity (hence influencing Long term potentiaton >> modifying the weights of the connections between neurons).

I'm aware that some research teams out there are already working on trying to integrate these cells into the neuronal connection model through the trypartite synapse model.  Michael Halassa, Tommasso Fellin, and others are creating computational models to model the interaction between neurons and glial cells, however, I don't know to what extent can astrocytes and other glial cells (like Bergman glia) be incorporated into Connectomics... maybe create astrocyte connectomics? That would be interesting. 

This is a very general paper on the topic:

http://journal.frontiersin.org/Journal/10.3389/fncom.2012.00065/full

**Comment by jovo** [comment]
did u get an ok answer in class today?

On Wednesday, February 4, 2015, SandyaS72 <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

>  I don't know about when you look at it from a neuron by neuron
> perspective, but in lots of cases, you look at connectivity on a larger
> more region by region basis, where nodes are regions. And in cases where
> you're measuring functional connectivity, which is based on activity, if
> the other cells affected activity in some way, I'm guessing that would get
> accounted for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/29#issuecomment-72917240>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by allym** [comment]
Astrocyte connectomics would be a fun venture :) And yes I did, class was very helpful, thanks jovo and everyone!
