### ISSUE TITLE
Question: Defining edges in neural graphs

### ISSUE THREAD

**Issue by kristinmg** [Statistical-Connectomics-Sp15/intro#3]
What is the most common way of defining edges between nodes in a neural graph in humans and can you give an example of how it would be used for real world problems?

**Comment by jovo** [comment]
see Craddock13a in google drive for answer to first question.
lemme know if its not there.

answer to 2nd question is in an article called: Clinical applications of
the functional connectome

 please post it in the goolge drive for others too?
