### ISSUE TITLE
Atlases

### ISSUE THREAD

**Issue by mblohr** [Statistical-Connectomics-Sp15/intro#32]
What are "Atlases?"

**Comment by willgray** [comment]
An atlas is simply a map (like what a "normal human" means when they say atlas).  There are a variety of brain atlases that are used for different purposes and at different scales.  I see these a lot in MR brain mapping (e.g., the Desikan atlas); another notable example from light microscopy is the Allen Brain Atlas (http://www.brain-map.org/).  

Atlases give scientists something to relate their data to, and usually contain known "features" or landmarks or parcellations to aid in analysis.
