### ISSUE TITLE
Brain Similarity

### ISSUE THREAD

**Issue by imichaelnorris** [Statistical-Connectomics-Sp15/intro#40]
How similar are the brains of different animal species when we create brain graphs? Can we analyze similar brain regions in humans and mice and compare graphs to get any sort of meaningful comparison?

**Comment by SandyaS72** [comment]
I'm guessing that depends on how you define 'similarity' for graphs.... for humans and mice, for example, there's an obvious difference in size, but if you want to think about some sort of structural similarity/difference independent of number of nodes/edges, you'd have to define a way to compute that.

**Comment by jovo** [comment]
note that defining metrics in graph space is an important and actively
researched area!

On Wednesday, February 4, 2015, SandyaS72 <notifications@github.com> wrote:

>  I'm guessing that depends on how you define 'similarity' for graphs....
> for humans and mice, for example, there's an obvious difference in size,
> but if you want to think about some sort of structural
> similarity/difference independent of number of nodes/edges, you'd have to
> define a way to compute that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/40#issuecomment-72918023>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by ajulian3** [comment]
I would perform an analysis by standardizing across size and functionality of both human and mice brains and linearly map the data in order to run a comparison. Specifically, if I assign functional tasks to the patients (humor me regarding the mice) I'd run a detection algorithm on the tasks and eventually run a  cross validation test to analyze independence.

**Comment by imichaelnorris** [comment]
Thanks!

**Comment by jovo** [comment]
indeed! how would you define similarity formally? or distance, in case that
is easier?

On Wednesday, February 4, 2015, SandyaS72 <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

>  I'm guessing that depends on how you define 'similarity' for graphs....
> for humans and mice, for example, there's an obvious difference in size,
> but if you want to think about some sort of structural
> similarity/difference independent of number of nodes/edges, you'd have to
> define a way to compute that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/40#issuecomment-72918023>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
