### ISSUE TITLE
Choosing matrices in Statistical Decision Theory

### ISSUE THREAD

**Issue by allym** [Statistical-Connectomics-Sp15/intro#41]
At the end of the lecture, we concluded that there are 2^ (n choose 2) matrices to describe any graph but that since we can't analyze all of them, we pick several for analysis. How do we pick which ones we analyze? Is it done through random selection?

**Comment by jovo** [comment]
i analyze either observed ones, or samples from some random graph
distribution.

On Tue, Feb 3, 2015 at 2:03 PM, allym <notifications@github.com> wrote:

>  At the end of the lecture, we concluded that there are 2^ (n choose 2)
> matrices to describe any graph but that since we can't analyze all of them,
> we pick several for analysis. How do we pick which ones we analyze? Is it
> done through random selection?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/41>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by allym** [comment]
Cool, that definitely makes a lot of sense, thank you! :)
