### ISSUE TITLE
Hereditary Features and Graphs

### ISSUE THREAD

**Issue by DSP137** [Statistical-Connectomics-Sp15/intro#50]
So, I am sure there is research on this, but if anyone has any idea where to look or knows something themselves, I'd appreciate the knowledge. 
We've been talking about how we partition the neurons into regions of the brain and look at which connections are made and how many of those connections are made to various other parts of the brain. There was another question about what research has been done with respect to Alzheimer's and other such diseases. 
I am wondering if there is also research being done comparing neural networks in patients who are biologically related verses those who are not related. Some diseases are said to have hereditary aspects. Where do these claims come from? How can we tell by looking at the graphs of these patients? Is there a particular part of the brain that is responsible for whether or not someone gets Alzheimer's (in which case, we would be primarily interested in the connections around and within this particular region)? Is there a way to predict whether or not someone will develop such a disease later in life based on the patterns seen in their own brain graphs as compared to the brain graphs of their relatives?

**Comment by gkiar** [comment]
"I am wondering if there is also research being done comparing neural networks in patients who are biologically related verses those who are not related"
No idea, haven't found anything through a quick search but to my knowledge no such study exists (or has at least been published).

"Some diseases are said to have hereditary aspects. Where do these claims come from?"
Well, currently, to my knowledge all of these so-called claims come from genetic evidence or observation.

"How can we tell by looking at the graphs of these patients? Is there a particular part of the brain that is responsible for whether or not someone gets Alzheimer's (in which case, we would be primarily interested in the connections around and within this particular region)?"
Good question. Some such conditions are considered 'connectopathies', which means that the connectivity structure is different. Based on the disease, the connectivity difference we may be observing could have wildly different regions involved and in the case of Alzheimer's, which (according to some quick googling) consists of shrinking of the cortex and hippocampus, that could definitely be a good place to start looking for connectivity differences.

"Is there a way to predict whether or not someone will develop such a disease later in life based on the patterns seen in their own brain graphs as compared to the brain graphs of their relatives?"
No idea. You should do the study and let us know. :)
