### ISSUE TITLE
Available Datasets

### ISSUE THREAD

**Issue by ElanHR** [Statistical-Connectomics-Sp15/intro#58]
Given that MRCAP allows for a fairly straightforward and convenient way of generating adjacency matrices given MRI data, what sorts of datasets are available for research?

Searching online I found code for implementations but no mentions of datasets (though I imagine they could require some registration to access ).

**Comment by ajulian3** [comment]
The main issues with these datasets is the accessibility. From my experience, labs need to pay for access through grants or be a part of a research symposium. Accordingly, it can be difficult performing independent research on neural network data.

**Comment by gkiar** [comment]
You're right, there is definitely issues with confidentiality in some cases, but there are actually lots of public datasets. We host some of them, preprocessed, on our website here (if you want a taste): http://openconnecto.me/data/public/MR/MIGRAINE_v1_0/

All of these datasets are completely public and available for processing by just about anyone.

**Comment by jovo** [comment]
also tell them about disa's webpage for downloading the graphs.

On Thursday, February 5, 2015, Greg Kiar <notifications@github.com> wrote:

>  Closed #58
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/58>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/58#event-231217108>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
