### ISSUE TITLE
MR Connectome Weights?

### ISSUE THREAD

**Issue by willgray** [Statistical-Connectomics-Sp15/intro#6]
To measure MR graph connectivity, we have the option of counting and then binarizing, or using some sort of continuous measure (e.g., log of counts).  Do we have any evidence that one is better than the other or that any are "right(er)?"  I think no, and that we have to measure against repeatability or classification or I suppose an anatomical prior...  But choosing a value seems like a very squishy process...

**Comment by jovo** [comment]
there is a bias/variance trade-off...what are the bias/variance trade-offs
for the 2 different approaches?

**Comment by willgray** [comment]
Continuous data is susceptible to variance because small fluctuations in the measurements will affect results.

Binarized data is more susceptible to bias, because we could be disregarding an important aspect of the signal. 

Log scale might be a somewhat balanced approach as sort of a "low pass filter."

**Comment by jovo** [comment]
+1
