### ISSUE TITLE
I missed a lecture, and I'm not sure where we get the value 2^n^2, which seems to be used fairly often; where did we get this number, and what is its significance?

### ISSUE THREAD

**Issue by adjordan** [Statistical-Connectomics-Sp15/intro#60]

**Comment by imichaelnorris** [comment]
It's the total amount of possible graphs with N labeled nodes. Each node can have at most 1 edge between them, but it could obviously have zero. If we count every possible combination of graphs, it is 2^n^2.

**Comment by imichaelnorris** [comment]
Also see en.wikipedia.org/wiki/Graph_enumeration
