### ISSUE TITLE
Question: Is MR /fine/ enough?

### ISSUE THREAD

**Issue by gkiar** [Statistical-Connectomics-Sp15/intro#7]
Do you think that MR imaging, and the connectomes estimated as a result, provide a fine enough resolution to gain insight into the behaviour or traits of the individual? Do you think that so-called "connectopathies" like schizophrenia or autism can be observed in structural differences at this scale?

**Comment by jovo** [comment]
what do you think?

**Comment by gkiar** [comment]
I think that depends on the scale at which a connectopathy exists. It's unclear (at least to me) whether inter- or intra-region connectivity plays a more significant role in certain behaviours. If it's the former, then MR could likely identify this; the latter, less clear but I imagine not.
