### ISSUE TITLE
Defining Operations with Graphs

### ISSUE THREAD

**Issue by adjordan** [Statistical-Connectomics-Sp15/intro#9]
I was slightly confused on what we were supposed to leave this lecture with; is there no standard for what the sum of two graphs is? Are we just going to pick one of many standards? If there are multiple accepted ways to sum graphs, why hasn't a convention been adopted (such as adopting the convention that the outside of a cell is 0 mV)?

**Comment by jovo** [comment]
great question!
the point the lecture was that it really is not clear how to add graphs.
so, we are going to develop other tools to be able to do statistics on them.
next lecture, we will begin introducing probability theory, and
distributions of graphs,
and hopefully some clarity will ensue!
